accounts/urls.py
from django.contrib.auth import logout
from django.urls import path
from .views import login_view, logout_view


app_name='accounts'
urlpatterns=[
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
    

]

datacollection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('studentdata.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

studentdata/urls.py
from django.urls import path
from .views import create_student, edit_student_data, home, individual_student, view_students

app_name = 'studentdata'
urlpatterns = [
    path('', home, name='home'),
    path('create-student/',create_student,name='create_student'),
    path('students/',view_students,name='students'),
    path('student/<int:id>/',individual_student,name='individual_students'),
    path('student/edit/<int:id>/',edit_student_data,name='edit_student'),

    ]

templates/about.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		
		<title>Creativo</title>

		<!-- Loading third party fonts -->
		<link href="fonts/font-awesome.min.css" rel="stylesheet" type="text/css">

		<!-- Loading main css file -->
		<link rel="stylesheet" href="style.css">
		
		<!--[if lt IE 9]>
		<script src="js/ie-support/html5.js"></script>
		<script src="js/ie-support/respond.js"></script>
		<![endif]-->

	</head>


	<body>
		
		<div class="site-content">
			
			<header class="site-header">
				<div class="container shrinked">
					<a href="about.html" class="button">About Us</a>
					<h1 class="logo"><a href="index.html">Creativo</a></h1>
					<a href="contact.html" class="button">Contact</a>
				</div>	<!-- .container -->
			</header> <!-- .site-header -->

			<main class="main-content">
				<div class="container shrinked">
					<h1 class="section-title">Who we <span>really are?</span></h1>

					<div class="entry-content">
						<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p> 

						<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt.</p>
					</div>

					<div class="team-section row">
						<div class="team">
							<img src="dummy/team-1.jpg" alt="Martin Lorenz" class="team-image">
							<h2 class="team-name">Martin Lorenz</h2>
						</div>
						<div class="team">
							<img src="dummy/team-2.jpg" alt="Tina Montgomery" class="team-image">
							<h2 class="team-name">Tina Montgomery</h2>
						</div>
						<div class="team">
							<img src="dummy/team-3.jpg" alt="Peter Wang" class="team-image">
							<h2 class="team-name">Peter Wang</h2>
						</div>
						<div class="team">
							<img src="dummy/team-4.jpg" alt="Sarah Stone" class="team-image">
							<h2 class="team-name">Sarah Stone</h2>
						</div>
					</div>

				</div>	<!-- .container -->
			</main> <!-- .main-content -->

			<footer class="site-footer">
				<div class="container shrinked">
					
					<div class="social-links">
						<a href="#"><i class="fa fa-facebook"></i></a>
						<a href="#"><i class="fa fa-google-plus"></i></a>
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-pinterest"></i></a>
					</div> <!-- .social-links -->

					<div class="colophon">Copyright 2014 Creativo. All right reserved</div>

				</div>	<!-- .container -->
			</footer> <!-- .site-footer -->

		</div>

		<script src="js/jquery-1.11.1.min.js"></script>
		<script src="js/plugins.js"></script>
		<script src="js/app.js"></script>
		
	</body>

</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		
		<title>Creativo</title>

		<!-- Loading third party fonts -->
		<link href="fonts/font-awesome.min.css" rel="stylesheet" type="text/css">

		<!-- Loading main css file -->
		<link rel="stylesheet" href="style.css">
		
		<!--[if lt IE 9]>
		<script src="js/ie-support/html5.js"></script>
		<script src="js/ie-support/respond.js"></script>
		<![endif]-->

	</head>


	<body>
		
		<div class="site-content">
			
			<header class="site-header">
				<div class="container shrinked">
					<a href="about.html" class="button">About Us</a>
					<h1 class="logo"><a href="index.html">Creativo</a></h1>
					<a href="contact.html" class="button">Contact</a>
				</div>	<!-- .container -->
			</header> <!-- .site-header -->

			<main class="main-content">
				<div class="container shrinked">
					<h1 class="section-title">Have questions? <span>Contact us!</span></h1>

					<div class="entry-content">
						<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p> 
					</div>

					<div class="row contact-section">
						<form action="" class="contact-form">
							<div class="col-sm-6">
								<div class="control">
									<input type="text" placeholder="Name...">
									<i class="fa fa-user"></i>
								</div>
								<div class="control">
									<input type="text" placeholder="Email...">
									<i class="fa fa-envelope"></i>
								</div>
								<div class="control">
									<input type="text" placeholder="Website...">
									<i class="fa fa-link"></i>
								</div>
							</div>
							<div class="col-sm-6">
								<div class="control">
									<textarea placeholder="Message..."></textarea>
									<i class="fa fa-pencil"></i>
								</div>

								<div class="right-aligned">
									<input type="submit" value="Send Message">
								</div>
							</div>
						</form>
					</div>

				</div>	<!-- .container -->
			</main> <!-- .main-content -->

			<footer class="site-footer">
				<div class="container shrinked">
					
					<div class="social-links">
						<a href="#"><i class="fa fa-facebook"></i></a>
						<a href="#"><i class="fa fa-google-plus"></i></a>
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-pinterest"></i></a>
					</div> <!-- .social-links -->

					<div class="colophon">Copyright 2014 Creativo. All right reserved</div>

				</div>	<!-- .container -->
			</footer> <!-- .site-footer -->

		</div>

		<script src="js/jquery-1.11.1.min.js"></script>
		<script src="js/plugins.js"></script>
		<script src="js/app.js"></script>
		
	</body>

</html>

templates/index.html
{% extends 'wrapper.html' %}{% load static %}{% block wrapper %} {% include 'nav.html' %}

<main class="main-content" style="height: 69vh">
  <div class="container">
    <div class="row justify-content-around">
      <div class="col-md-6 col-12 d-flex flex-column align-items-center">
        <img src="{% static 'images/morelogo.svg' %}" alt="" />
        <p class="text-center">
          MORE 2019) is a certified programme initiated by IT-Kerala, Kerala state RUTRONIX is the ultimate Microsoft office bundle (Release 2019). This course covers a wide range of topics done in an extremely professional manner and helps the learners to accomplish e- regular tasks easily and with
          greater efficiency, Microsoft Office is the utmost choice of many office professionals and useful for individuals for their day-to-day tasks to an extent. This course can walk you through creating professional-quality documents, organize and analyze information, function mathematical
          calculations, and create dynamic slide presentations more digitally and effectively. This course will help you master MS Office2019, reduce your MS Office frustrations and help you claw back the precious time you spend getting lost in these powerful business applications.
        </p>
        <a href="{% url 'studentdata:students' %}" class="button">Students</a>
      </div>
    </div>
<div class="row">
  <div class="col-12">
      <div class="embed-responsive embed-responsive-16by9">
    <video class="embed-responsive-item" src="https://www.youtube.com/embed/tgbNymZ7vqY"></video>
  </div>
  </div>
</div>
  </div>
  <!-- .container -->
</main>
<!-- .main-content -->

<footer class="text-center text-lg-start">
  <!-- Copyright -->
  <!-- <div class="container">

	  <div class="social-links">
		  <a href="#"><i class="bi bi-facebook"></i></a>
		  <a href="#"><i class="bi bi-google-plus"></i></a>
		  <a href="#"><i class="bi fa-twitter"></i></a>
		  <a href="#"><i class="bi fa-pinterest"></i></a>
		</div>
	</div> -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2020 Copyright:
    <a class="text-white" href="#">Groware </a>
  </div>
  <!-- Copyright -->
</footer>

{% endblock wrapper %}

templates/individual-student.html
{% extends 'wrapper.html' %} {% block wrapper %} {% include 'nav.html' %}
<div class="container-fluid mt-5">
  <div class="row">
    <div class="col-md">
      <div class="card border-0">
        <div class="card-header" id="light-blue-accent-4">
          <h5>Student Information</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    <table class="table table-dark" style="height: 100%;">
                        <tr>
                            <td>
                                <strong>Name:</strong> 
                            </td>
                            <td>
                                {{student.name}}
                            </td>
                        </tr>
                            <td>
                                <strong>Email:</strong> 
                            </td>
                            <td>
                                {{student.email}}
                            </td>
                        </tr>
                            <td>
                                <strong>Phone:</strong> 
                            </td>
                            <td>
                                {{student.phone}}
                            </td>
                        </tr>
                            <td>
                                <strong>Address:</strong> 
                            </td>
                            <td>
                                {{student.address}}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>Date of Birth:</strong> 
                            </td>
                            <td>
                                {{student.dob}}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>Course:</strong> 
                            </td>
                            <td>
                                {{student.course}}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>Year Joined: </strong> 
                            </td>
                            <td>
                                {{student.year_joined}}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>Student Address:</strong> 
                            </td>
                            <td>
                                {{student.address}}
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="col-6 rounded-2 d-flex justify-content-center">
                    <img src="{{  student.photo.url }}" alt="{{student.name}}" class="img-fluid rounded-3" style="max-height:50vh;" />
                </div>
            </div>
                <div class="d-flex justify-content-center">
                    <a class="btn btn-outline-info  btn-sm btn-block m-2" href="{% url 'studentdata:edit_student' student.id %}">Update Student</a>
                    
                    <a class="btn btn-outline-info btn-sm btn-block m-2" href="{% url 'studentdata:create_student' %}">New Registration</a>
                </div>
        </div>
      </div>
    </div>
  </div>

  <br />
</div>
{% endblock wrapper %}

templates/login.html
{% extends 'wrapper.html' %} {% block wrapper %} 
{% include 'nav.html' %}

<div class="container mt-5">
    <div class="row">
        <div class="col-12">
            
            <div class="card">
                <div class="card-header">
                    Login
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        <div class="d-flex justify-content-end">
                            <input type="submit" value="Login" class="btn btn-info me-2">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock wrapper %}

templates/nav.html
{% load static %}
<header class="site-header py-2 mb-2">
  <div class="container">
    <div class="row justify-content-around">

      <div class="col-1 d-flex align-items-center justify-content-center"><a href="{% url 'studentdata:home' %}" class="button">Course</a></div>
      <div class="col-2 d-flex align-items-center justify-content-center">
        <div class="d-flex justify-content-center p-0 logo" style="max-height:120px;width:120px;">
          <img src="{% static 'images/RutronixLogoNew.svg' %}" class="d-inline-block"/>
        </div>

      </div>
      {% if request.user.is_authenticated %}
      <div class="col-1 d-flex align-items-center justify-content-center"><a href="{% url 'accounts:logout' %}" class="button">Logout</a></div>
      {% else %}
      <div class="col-1 d-flex align-items-center justify-content-center"><a href="{% url 'accounts:login' %}" class="button">Login</a></div>
      {% endif %}


    </div>
  </div>
  <!-- .container -->
</header>
<!-- .site-header -->

templates/students.html
{% extends 'wrapper.html' %}


{% block wrapper %}

{% include 'nav.html' %}
<div class="container-fluid mt-2">
     <div class="row align-content-stretch">
        <div class="col-md">
            <div class="card border-0">
                <div class="card-header">
                    <h5>{{request.user.first_name}} {{request.user.last_name}}</h5>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-center pt-3 pb-2">
                        <a class="btn btn-outline-info mx-2 btn-sm btn-block" href="{% url 'studentdata:home' %}">Home</a>
                    
                        <a class="btn btn-outline-info mx-2 btn-sm btn-block" href="{% url 'studentdata:create_student' %}">Add New Student</a>
                    </div>
                </div>
            </div>
        </div>
        
        
        <div class="col-md">
            <div class="card border-0">
                <div class="card-header">
                    <h5>Total Registrations</h5>
                </div>
                <div class="card-body">
                    <h1 style="text-align: center;">{{reg_count}}</h1>
                </div>
            </div>
        </div>
    </div>
      <div class="row mt-3">
    <div class="col-12">
      <div class="d-flex justify-content-between my-0 py-0">  
          <span class="fs-5 fw-bold lh-1">STUDENTS</span><a href="{% url 'studentdata:create_student' %}" class="btn text-white btn-primary btn-sm mt-0 mb-2 "> Add Student </a>
        </div>
      <hr />
      <div class="card border-0">
        <div class="card-body">
            
            <table class="table table-sm border-0 text-white">
                <tr>
                    
                    <th>Student</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>View Details</th>
                </tr>
                {% for student in students %}
                <tr>
                    
                    <td>{{student.name}}</td>
                    <td>{{student.email}}</td>
                    <td>{{student.phone}}</td>
                    <td><a href="{% url 'studentdata:individual_students' student.id %}" class="btn btn-info text-dark">View</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    </div>
  </div>
</div>
</div>
{% endblock wrapper %}

templates/wrapper.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="" type="image/x-icon" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=MuseoModerno:wght@300;500;700&family=Raleway:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" />

    <link rel="stylesheet" href='{% static "css/main.css" %}' />
    <!-- <link rel="stylesheet" href='{% static "css/style.css" %}' /> -->

    <title>{{title}}</title>
  </head>
  <body>
        {% block wrapper %} 
        
        {% endblock wrapper %}
    <!-- <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>